fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PROD_DWH
  SRC_FIVETRAN_RETAIL:
    database: FIVETRAN_DATABASE
    schema: RETAIL_DATA
  SRC_FIVETRAN_SAP:
    database: SAP_DEMO
    schema: SAP_ERP_DATA_DEMO_SAP
  STAGE:
    database: DOUG_DB
    schema: PROD_STG
name: Production
type: Environment
