fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PROD_DWH
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SOURCE:
    database: ""
    schema: ""
  STAGE:
    database: DOUG_DB
    schema: PROD_STG
name: Production
type: Environment
