fileVersion: 1
id: "121"
mappingDefinitions:
  BRONZE:
    database: DOUG_DB
    schema: BRONZE
  GOLD:
    database: DOUG_DB
    schema: PRD_GOLD
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SILVER:
    database: DOUG_DB
    schema: PRD_SILVER
name: Production
type: Environment
