fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PRD_GOLD
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  STAGE:
    database: DOUG_DB
    schema: PRD_SILVER
name: Production Snowflake
type: Environment
