fileVersion: 1
id: "121"
mappingDefinitions:
  DW:
    database: ""
    schema: ""
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SOURCE:
    database: ""
    schema: ""
  STAGE:
    database: ""
    schema: ""
name: Production Snowflake
type: Environment
