fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PRD_GOLD
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SRC_FIVETRAN_RETAIL:
    database: FIVETRAN_DATABASE
    schema: RETAIL_DATA
  SRC_SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  SRC_WEATHER:
    database: COALESCE_SAMPLE_DATA
    schema: JSON
  STAGE:
    database: DOUG_DB
    schema: PRD_SILVER
name: Production Snowflake
type: Environment
