fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PROD_DWH
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SRC_FIVETRAN_RETAIL:
    database: FIVETRAN_DATABASE
    schema: RETAIL_DATA
  SRC_SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  SRC_WEATHER:
    database: COALESCE_SAMPLE_DATABASE
    schema: WEATHER
  STAGE:
    database: DOUG_DB
    schema: PROD_STG
name: Production
type: Environment
