fileVersion: 1
id: "121"
mappingDefinitions:
  BRONZE:
    database: DOUG_DB
    schema: BRONZE
  GOLD:
    database: DOUG_DB
    schema: PRD_GOLD
  PLATINUM:
    database: DOUG_DB
    schema: PRD_GOLD
  SILVER:
    database: DOUG_DB
    schema: PRD_SILVER
name: Production Snowflake
type: Environment
