fileVersion: 1
id: "121"
mappingDefinitions:
  DWH:
    database: DOUG_DB
    schema: PROD_DWH
  SRC_SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  STAGE:
    database: DOUG_DB
    schema: PROD_STG
name: Production Snowflake
type: Environment
