fileVersion: 1
id: "8"
mappingDefinitions:
  SRC_AADB:
    database: CAMBRIDGE_DEV
    schema: AADB
  SRC_BROOKLYN:
    database: CAMBRIDGE_DEV
    schema: BROOKLYN
  SRC_CMDB:
    database: CAMBRIDGE_DEV
    schema: CMDB
  SRC_COMMON:
    database: CAMBRIDGE_DEV
    schema: COMMON
  SRC_CRMERP:
    database: CAMBRIDGE_DEV
    schema: CRMERP
  SRC_GOVERN:
    database: CAMBRIDGE_DEV
    schema: GOVERN
  SRC_IMISDE:
    database: CAMBRIDGE_DEV
    schema: IMISDE
  STAGE:
    database: CAMBRIDGE_PROD
    schema: SILVER
name: Production
type: Environment
