@id("gold-vendor-trip-summary")
@nodeType("456")
SELECT
    VC.VENDOR_ID,
    VC.VENDOR_NAME,
    VC.PHONE_DIGITS,
    VC.DRIVERS,
    VC.HQ_ADDRESS1,
    VC.HQ_CITY,
    VC.HQ_STATE,
    VC.HQ_COUNTRY,
    VC.HQ_ZIP,
    VC.VENDOR_TIER,
    VC.MARKET_TYPE,
    VA.TRIP_COUNT_7,
    VA.TRIP_DISTANCE_7,
    VA.FARE_AMOUNT_7,
    VA.RANK_FARE_7,
    VA.RANK_DISTANCE_7,
    VLS.TOP_5_ZONES
FROM {{ ref("SILVER", "STG_VENDOR_CLASSIFICATION") }} VC
JOIN {{ ref("SILVER", "STG_VENDOR_ACTIVITY_7") }} VA
    ON VC.VENDOR_ID = VA.VENDOR_ID
JOIN {{ ref("SILVER", "STG_VENDOR_LOCATION_SUMMARY_7") }} VLS
    ON VC.VENDOR_ID = VLS.VENDOR_ID
ORDER BY VA.RANK_FARE_7
