@id("fct-cab-trips-001")
@nodeType("455")
SELECT
    TRIP_ID @isBusinessKey,
    VENDOR_ID,
    PAYMENT_TYPE_ID,
    RATE_CODE_ID,
    PU_LOCATION_ID,
    DO_LOCATION_ID,
    PASSENGER_COUNT,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    MTA_TAX,
    IMPROVEMENT_SURCHARGE,
    CONGESTION_SURCHARGE,
    CBD_CONGESTION_FEE,
    AIRPORT_FEE,
    EXTRA,
    TOTAL_AMOUNT,
    STORE_AND_FWD_FLAG
FROM {{ ref("SILVER", "STG_CAB_TRIPS") }}
