@id("a1b2c3d4-0009-4000-8000-000000000009")
@nodeType("456")
SELECT
    "VC"."VENDOR_ID"       AS "VENDOR_ID",
    "VC"."VENDOR_NAME"     AS "VENDOR_NAME",
    "VC"."PHONE_DIGITS"    AS "PHONE_DIGITS",
    "VC"."DRIVERS"         AS "DRIVERS",
    "VC"."HQ_ADDRESS1"     AS "HQ_ADDRESS1",
    "VC"."HQ_CITY"         AS "HQ_CITY",
    "VC"."HQ_STATE"        AS "HQ_STATE",
    "VC"."HQ_COUNTRY"      AS "HQ_COUNTRY",
    "VC"."HQ_ZIP"          AS "HQ_ZIP",
    "VC"."VENDOR_TIER"     AS "VENDOR_TIER",
    "VC"."MARKET_TYPE"     AS "MARKET_TYPE",
    "VA"."TRIP_COUNT_7"    AS "TRIP_COUNT_7",
    "VA"."TRIP_DISTANCE_7" AS "TRIP_DISTANCE_7",
    "VA"."FARE_AMOUNT_7"   AS "FARE_AMOUNT_7",
    "VA"."RANK_FARE_7"     AS "RANK_FARE_7",
    "VA"."RANK_DISTANCE_7" AS "RANK_DISTANCE_7",
    "VLS"."TOP_5_ZONES"    AS "TOP_5_ZONES"
FROM {{ ref('SILVER', 'STG_VENDOR_CLASSIFICATION') }} "VC"
JOIN {{ ref('SILVER', 'STG_VENDOR_ACTIVITY_7') }} "VA"
    ON "VC"."VENDOR_ID" = "VA"."VENDOR_ID"
JOIN {{ ref('SILVER', 'STG_VENDOR_LOCATION_SUMMARY_7') }} "VLS"
    ON "VC"."VENDOR_ID" = "VLS"."VENDOR_ID"
