@id("ed143cc0-1a63-4819-bb36-8e6ba4aac9a8")
@nodeType("456")
WITH DRV AS (
SELECT
     "DRIVER_ID" AS "DRIVER_ID",
     "VENDOR_ID" AS "VENDOR_ID",
     "FIRST_NAME" AS "FIRST_NAME",
     "LAST_NAME" AS "LAST_NAME",
     FIRST_NAME || LAST_NAME AS FULL_NAME,
     "LICENSE_NUMBER" AS "LICENSE_NUMBER",
     "LICENSE_EXPIRY" AS "LICENSE_EXPIRY",
     "PHONE" AS "PHONE",
     "EMAIL" AS "EMAIL",
     "HIRE_DATE" AS "HIRE_DATE",
     "RATING" AS "RATING",
     "IS_ACTIVE" AS "IS_ACTIVE"
FROM {{ ref('BRONZE', 'DRIVERS') }} )

SELECT * FROM DRV