@id("a1b2c3d4-0004-4000-8000-000000000004")
@nodeType("456")
SELECT
    "BV"."VENDOR_ID"      AS "VENDOR_ID",
    "BV"."VENDOR_NAME"    AS "VENDOR_NAME",
    "CP"."PHONE_DIGITS"   AS "PHONE_DIGITS",
    "CP"."DRIVERS"        AS "DRIVERS",
    "CP"."HQ_ADDRESS1"    AS "HQ_ADDRESS1",
    "CP"."HQ_CITY"        AS "HQ_CITY",
    "CP"."HQ_STATE"       AS "HQ_STATE",
    "CP"."HQ_COUNTRY"     AS "HQ_COUNTRY",
    "CP"."HQ_ZIP"         AS "HQ_ZIP"
FROM {{ ref('SILVER', 'STG_BASE_VENDOR') }} "BV"
JOIN {{ ref('SILVER', 'STG_VENDOR_CLEAN_PHONE') }} "CP"
    ON "BV"."VENDOR_ID" = "CP"."VENDOR_ID"
