@id("stg-vendor-activity-7-001")
@nodeType("456")
SELECT
    VENDOR_ID,
    COUNT(1) AS TRIP_COUNT_7,
    SUM(TRIP_DISTANCE) AS TRIP_DISTANCE_7,
    SUM(FARE_AMOUNT) AS FARE_AMOUNT_7,
    RANK() OVER (ORDER BY SUM(FARE_AMOUNT) DESC) AS RANK_FARE_7,
    RANK() OVER (ORDER BY SUM(TRIP_DISTANCE) DESC) AS RANK_DISTANCE_7
FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }}
JOIN {{ ref("BRONZE", "LOCATION") }} ON YELLOW_CAB_TRIPS.PU_LOCATION_ID = LOCATION.LOCATION_ID
WHERE TO_DATE(PICKUP_DATETIME) BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
GROUP BY 1
