@id("9d6c4565-a5dd-47f9-b4c1-9dacbbc978f9")
@nodeType("446")
SELECT
     "PAYMENT_TYPE_ID" AS "PAYMENT_TYPE_ID",
     "PAYMENT_TYPE" AS "PAYMENT_TYPE"
FROM {{ ref('BRONZE', 'PAYMENT_TYPE') }} "PAYMENT_TYPE"