@id("4765af8b-202f-49a7-b27a-6f3eb41c1f65")
@nodeType("446")
SELECT
     "LOCATION_ID" AS "LOCATION_ID",
     "BOROUGH" AS "BOROUGH",
     "ZONE" AS "ZONE",
     "SERVICE_ZONE" AS "SERVICE_ZONE",
     "FILENAME" AS "FILENAME"
FROM {{ ref('BRONZE', 'LOCATION') }} "LOCATION"