@id("a1b2c3d4-0007-4000-8000-000000000007")
@nodeType("456")
SELECT
    "YELLOW_CAB_TRIPS"."VENDOR_ID"              AS "VENDOR_ID",
    "LOCATION"."ZONE"                           AS "ZONE",
    SUM("YELLOW_CAB_TRIPS"."FARE_AMOUNT")       AS "LOC_FARE_AMOUNT_7",
    COUNT(1)                                    AS "LOC_TRIP_COUNT_7"
FROM {{ ref('BRONZE', 'YELLOW_CAB_TRIPS') }} "YELLOW_CAB_TRIPS"
JOIN {{ ref('BRONZE', 'LOCATION') }} "LOCATION"
    ON "YELLOW_CAB_TRIPS"."PU_LOCATION_ID" = "LOCATION"."LOCATION_ID"
WHERE TO_DATE("YELLOW_CAB_TRIPS"."PICKUP_DATETIME") BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
GROUP BY 1, 2
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "YELLOW_CAB_TRIPS"."VENDOR_ID", "LOCATION"."ZONE"
    ORDER BY SUM("YELLOW_CAB_TRIPS"."FARE_AMOUNT") DESC
) <= 5
