@id("b5c887fb-4222-4d70-942f-bcf971dfd7dc")
@nodeType("456")
@materializationType("view")
SELECT
     "DRIVER_ID" AS "DRIVER_ID",
     "VENDOR_ID" AS "VENDOR_ID",
     "FIRST_NAME" AS "FIRST_NAME",
     "LAST_NAME" AS "LAST_NAME",
     "LICENSE_NUMBER" AS "LICENSE_NUMBER",
     "LICENSE_EXPIRY" AS "LICENSE_EXPIRY",
     "PHONE" AS "PHONE",
     "EMAIL" AS "EMAIL",
     "HIRE_DATE" AS "HIRE_DATE",
     "RATING" AS "RATING",
     "IS_ACTIVE" AS "IS_ACTIVE"
FROM {{ ref('BRONZE', 'DRIVERS') }} "DRIVERS"