@id("870202ec-7c54-4e8e-8d94-f88f9f1194a7")
@nodeType("455")
SELECT
     "VENDOR_ID" AS "VENDOR_ID" @isBusinessKey,
     "HQ_ADDRESS_DETAILS" AS "HQ_ADDRESS_DETAILS",
     "PHONE" AS "PHONE",
     "DRIVERS" AS "DRIVERS",
     "VENDOR_NAME" AS "VENDOR_NAME"
FROM {{ ref('SILVER', 'INS_VENDOR') }} "INS_VENDOR"