@id("stg-vendor-top-zones-7-001")
@nodeType("456")
WITH vendor_location_activity_7 AS (
    SELECT
        YELLOW_CAB_TRIPS.VENDOR_ID,
        LOCATION.ZONE,
        SUM(FARE_AMOUNT) AS LOC_FARE_AMOUNT_7,
        COUNT(1) AS LOC_TRIP_COUNT_7
    FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }}
    JOIN {{ ref("BRONZE", "LOCATION") }} ON YELLOW_CAB_TRIPS.PU_LOCATION_ID = LOCATION.LOCATION_ID
    WHERE TO_DATE(PICKUP_DATETIME) BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
    GROUP BY 1, 2
    QUALIFY ROW_NUMBER() OVER (PARTITION BY YELLOW_CAB_TRIPS.VENDOR_ID, LOCATION.ZONE ORDER BY SUM(FARE_AMOUNT) DESC) <= 5
)
SELECT
    VENDOR_ID,
    LISTAGG(ZONE || ' ($' || TO_CHAR(LOC_FARE_AMOUNT_7, '9,999,999.00') || ')', ', ') WITHIN GROUP (ORDER BY LOC_FARE_AMOUNT_7 DESC) AS TOP_5_ZONES
FROM vendor_location_activity_7
GROUP BY 1
