@id("stg-vendor-activity-7")
@nodeType("456")
SELECT
    YCT.VENDOR_ID,
    COUNT(1) AS TRIP_COUNT_7,
    SUM(YCT.TRIP_DISTANCE) AS TRIP_DISTANCE_7,
    SUM(YCT.FARE_AMOUNT) AS FARE_AMOUNT_7,
    RANK() OVER (ORDER BY SUM(YCT.FARE_AMOUNT) DESC) AS RANK_FARE_7,
    RANK() OVER (ORDER BY SUM(YCT.TRIP_DISTANCE) DESC) AS RANK_DISTANCE_7
FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }} YCT
JOIN {{ ref("BRONZE", "LOCATION") }} LOC
    ON YCT.PU_LOCATION_ID = LOC.LOCATION_ID
WHERE TO_DATE(YCT.PICKUP_DATETIME) BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
GROUP BY 1
