@id("b02cca57-9b8d-4bdb-a6c9-9a05e9d3439a")
@nodeType("456")
SELECT
     VENDOR."VENDOR_ID" AS "VENDOR_ID",
     VENDOR_DETAILS."HQ_ADDRESS_DETAILS" AS "HQ_ADDRESS_DETAILS",
     VENDOR_DETAILS."PHONE" AS "PHONE",
     VENDOR_DETAILS."DRIVERS" AS "DRIVERS",
     VENDOR."VENDOR_NAME" AS "VENDOR_NAME"
FROM {{ ref('BRONZE', 'VENDOR_DETAILS') }} "VENDOR_DETAILS"
INNER JOIN {{ ref('BRONZE', 'VENDOR') }} "VENDOR"
ON "VENDOR_DETAILS".VENDOR_ID = "VENDOR".VENDOR_ID