@id("stg-cab-trips-001")
@nodeType("456")
SELECT
    TRIP_ID,
    CAST(VENDOR_ID AS NUMBER(38,0)) AS VENDOR_ID,
    CAST(PAYMENT_TYPE_ID AS NUMBER(38,0)) AS PAYMENT_TYPE_ID,
    CAST(RATE_CODE_ID AS NUMBER(38,0)) AS RATE_CODE_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    CAST(PU_LOCATION_ID AS NUMBER(38,0)) AS PU_LOCATION_ID,
    CAST(DO_LOCATION_ID AS NUMBER(38,0)) AS DO_LOCATION_ID,
    CAST(PASSENGER_COUNT AS NUMBER(38,0)) AS PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    MTA_TAX,
    IMPROVEMENT_SURCHARGE,
    CONGESTION_SURCHARGE,
    CBD_CONGESTION_FEE,
    AIRPORT_FEE,
    EXTRA,
    TOTAL_AMOUNT,
    STORE_AND_FWD_FLAG
FROM {{ ref("BRONZE", "CAB_TRIPS") }}
UNION ALL
SELECT
    TRIP_ID,
    CAST(VENDOR_ID AS NUMBER(38,0)) AS VENDOR_ID,
    CAST(PAYMENT_TYPE_ID AS NUMBER(38,0)) AS PAYMENT_TYPE_ID,
    CAST(RATE_CODE_ID AS NUMBER(38,0)) AS RATE_CODE_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    CAST(PU_LOCATION_ID AS NUMBER(38,0)) AS PU_LOCATION_ID,
    CAST(DO_LOCATION_ID AS NUMBER(38,0)) AS DO_LOCATION_ID,
    CAST(PASSENGER_COUNT AS NUMBER(38,0)) AS PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    MTA_TAX,
    IMPROVEMENT_SURCHARGE,
    CONGESTION_SURCHARGE,
    CBD_CONGESTION_FEE,
    AIRPORT_FEE,
    EXTRA,
    TOTAL_AMOUNT,
    STORE_AND_FWD_FLAG
FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }}
