@id("stg-vendor-enriched-001")
@nodeType("456")
WITH vendor_details AS (
    SELECT
        VENDOR_ID,
        REGEXP_REPLACE(PHONE, '[^0-9]', '') AS PHONE_DIGITS,
        DRIVERS,
        HQ_ADDRESS_DETAILS:ADDRESS::STRING AS HQ_ADDRESS1,
        HQ_ADDRESS_DETAILS:CITY::STRING AS HQ_CITY,
        HQ_ADDRESS_DETAILS:STATE::STRING AS HQ_STATE,
        HQ_ADDRESS_DETAILS:COUNTRY::STRING AS HQ_COUNTRY,
        HQ_ADDRESS_DETAILS:ZIP::STRING AS HQ_ZIP
    FROM {{ ref("BRONZE", "VENDOR_DETAILS") }}
)
SELECT
    v.VENDOR_ID,
    v.VENDOR_NAME,
    vd.PHONE_DIGITS,
    vd.DRIVERS,
    vd.HQ_ADDRESS1,
    vd.HQ_CITY,
    vd.HQ_STATE,
    vd.HQ_COUNTRY,
    vd.HQ_ZIP,
    CASE 
        WHEN vd.DRIVERS >= 200 THEN 'ENTERPRISE'
        WHEN vd.DRIVERS >= 50 THEN 'MID_SIZE'
        ELSE 'SMALL'
    END AS VENDOR_TIER,
    CASE
        WHEN vd.HQ_COUNTRY = 'USA' THEN 'DOMESTIC'
        ELSE 'INTERNATIONAL'
    END AS MARKET_TYPE
FROM {{ ref("BRONZE", "VENDOR") }} v
JOIN vendor_details vd ON v.VENDOR_ID = vd.VENDOR_ID
