@id("a1b2c3d4-0006-4000-8000-000000000006")
@nodeType("456")
SELECT
    "YELLOW_CAB_TRIPS"."VENDOR_ID"                                       AS "VENDOR_ID",
    COUNT(1)                                                              AS "TRIP_COUNT_7",
    SUM("YELLOW_CAB_TRIPS"."TRIP_DISTANCE")                              AS "TRIP_DISTANCE_7",
    SUM("YELLOW_CAB_TRIPS"."FARE_AMOUNT")                                AS "FARE_AMOUNT_7",
    RANK() OVER (ORDER BY SUM("YELLOW_CAB_TRIPS"."FARE_AMOUNT") DESC)    AS "RANK_FARE_7",
    RANK() OVER (ORDER BY SUM("YELLOW_CAB_TRIPS"."TRIP_DISTANCE") DESC)  AS "RANK_DISTANCE_7"
FROM {{ ref('BRONZE', 'YELLOW_CAB_TRIPS') }} "YELLOW_CAB_TRIPS"
JOIN {{ ref('BRONZE', 'LOCATION') }} "LOCATION"
    ON "YELLOW_CAB_TRIPS"."PU_LOCATION_ID" = "LOCATION"."LOCATION_ID"
WHERE TO_DATE("YELLOW_CAB_TRIPS"."PICKUP_DATETIME") BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
GROUP BY 1
