@id("stg-vendor-details")
@nodeType("456")
SELECT
    VENDOR_ID,
    PHONE,
    DRIVERS,
    HQ_ADDRESS_DETAILS:ADDRESS::STRING AS HQ_ADDRESS1,
    HQ_ADDRESS_DETAILS:CITY::STRING AS HQ_CITY,
    HQ_ADDRESS_DETAILS:STATE::STRING AS HQ_STATE,
    HQ_ADDRESS_DETAILS:COUNTRY::STRING AS HQ_COUNTRY,
    HQ_ADDRESS_DETAILS:ZIP::STRING AS HQ_ZIP
FROM {{ ref("BRONZE", "VENDOR_DETAILS") }}
