@id("stg-vendor-location-activity-7")
@nodeType("456")
SELECT
    YCT.VENDOR_ID,
    LOC.ZONE,
    SUM(YCT.FARE_AMOUNT) AS LOC_FARE_AMOUNT_7,
    COUNT(1) AS LOC_TRIP_COUNT_7
FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }} YCT
JOIN {{ ref("BRONZE", "LOCATION") }} LOC
    ON YCT.PU_LOCATION_ID = LOC.LOCATION_ID
WHERE TO_DATE(YCT.PICKUP_DATETIME) BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
GROUP BY 1, 2
QUALIFY ROW_NUMBER() OVER (PARTITION BY YCT.VENDOR_ID, LOC.ZONE ORDER BY SUM(YCT.FARE_AMOUNT) DESC) <= 5
