@id("0ac00f48-4079-4249-826a-b85c5c2d07b5")
@nodeType("456")

WITH LOC AS (
SELECT
     "DRIVER_ID" AS "DRIVER_ID",
     "VENDOR_ID" AS "VENDOR_ID",
     "FIRST_NAME" AS "FIRST_NAME",
     "LAST_NAME" AS "LAST_NAME",
     FIRST_NAME||' ' ||LAST_NAME AS FULL_NAME,
     "LICENSE_NUMBER" AS "LICENSE_NUMBER",
     "LICENSE_EXPIRY" AS "LICENSE_EXPIRY",
     "PHONE" AS "PHONE",
     "EMAIL" AS "EMAIL",
     "HIRE_DATE" AS "HIRE_DATE",
     "RATING" AS "RATING",
     "IS_ACTIVE" AS "IS_ACTIVE"
FROM {{ ref('BRONZE', 'DRIVERS') }} )

SELECT * FROM LOC