fileVersion: 1
id: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
name: GOVCONFIG
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: SRC_GOVERN
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 88223c8c-5763-4cff-894a-90ff39f09793
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: CONFIGID
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c71b5d61-9659-4807-9fe4-d62f94bedf39
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: CONFIGTYPEID
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 72dc3a63-89de-40f6-96ee-7a68ed0448ba
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(1000)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 43c67e6c-9857-4d63-86d9-a09b57e1aeeb
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a43ee5a6-a8bd-43b0-8fb5-6476d1f32d0c
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 2e345300-d72e-4403-a63e-7be4f1626b39
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        name: CREATED_BY
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: dcb791d0-0271-4ff9-9980-a426c9103440
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: TIMESTAMP_NTZ(0)
        defaultValue: ""
        description: ""
        name: HVR_CAPTURE_TIME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: fe63a65e-a2d2-410b-8c57-418aa520e357
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_OP
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 0359e1cc-d677-4381-b05b-f9144f63900d
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(46)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_SEQUENCE
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2b85215-fb2f-48dc-aa5a-52c86b711eb2
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: TIMESTAMP_TZ(3)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_TIME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 03874ae2-6122-4c5b-bf61-d99ad993e4da
          stepCounter: b66b77ff-6c5e-4fdd-8641-5bc9a7da9417
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: SOURCE_CD
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: GOVCONFIG
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
