fileVersion: 1
id: ac71cb27-d27b-40de-ba52-6e9514223843
name: VWA_USER_SECURITY
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: VIEWS
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00f4ad8d-4434-48dd-b6ba-ef3f06542b02
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: LOGIN_NAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6ebdaf66-be13-47ad-ae42-895647abe585
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 58288aaa-1a2b-4378-ac37-4f596dbdffa1
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: LEVEL1_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 775e3af4-6c6f-45ed-b239-db3b9f134b02
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d70baf3c-dc9f-47c8-8794-0471bc060b50
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: LEVEL2_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 267f9ad9-49af-4b7c-8856-9891b24c5860
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 026f6e17-fe7b-4db2-b5f2-0d92f338dac4
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: LEVEL3_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a006ce3d-4341-4104-8dd4-44aec1283628
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bcb38c1e-a20e-4cc8-8495-dc296c679ba5
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: LEVEL4_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fea29b87-8c3e-4e5e-9c1b-7b8ee8f64aca
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cdb1b68c-1c03-4d02-bf98-74ed3f6665ae
          stepCounter: ac71cb27-d27b-40de-ba52-6e9514223843
        config: {}
        dataType: VARCHAR(16777216)
        description: ""
        name: BRAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f68681ff-f7e9-4a09-88ed-3d1fa6a2b64a
                stepCounter: 296e1f47-2109-4d4d-9e14-f4916e072666
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: STAGE
            nodeName: VW_USER_SECURITY
        join:
          joinCondition: FROM {{ ref('STAGE', 'VW_USER_SECURITY') }} "VW_USER_SECURITY"
        name: VWA_USER_SECURITY
        noLinkRefs: []
  name: VWA_USER_SECURITY
  overrideSQL: false
  schema: ""
  sqlType: "17"
  type: sql
  version: 1
type: Node
