config:
  entities:
    nodeTypes:
      "173":
        defaultStorageLocation: STAGE
        isDisabled: false
      "188":
        defaultStorageLocation: DWH
        isDisabled: false
      "194":
        defaultStorageLocation: DWH
        isDisabled: false
      "204":
        defaultStorageLocation: STAGE
        isDisabled: false
      "205":
        defaultStorageLocation: DWH
        isDisabled: false
      "248":
        defaultStorageLocation: DWH
        isDisabled: false
  packageVariables: ""
fileVersion: 1
id: "@coalesce/base-node-types"
name: Base
packageID: "@coalesce/base-node-types"
releaseID: 360da3b1-79c1-4d68-8847-90302f2a7b61
type: Package
