name: Refresh Data

on:
  # Set a schedule using cron
  schedule:
  - cron: "0 9 1 * *"
  
  # This option allows the workflow to be triggered manually
  workflow_dispatch:
  
env:
  COA_VERSION: latest # Versions released on NPM here: https://www.npmjs.com/package/@coalescesoftware/coa  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.19.0

    - name: Write Snowflake Key to file
      run: |
        umask 077
        printf '%s' "${{ secrets.SF_PRIVATE_KEY }}" > key.pem
        
    - name: Write Coa Config 
      run: echo '${{ secrets.COA_CONFIG }}' >> COA_CONFIG
    
    - name: Install Coalesce CLI tool
      run: npm list | grep "@coalescesoftware/coa@${{ env.COA_VERSION }}" || npm install @coalescesoftware/coa@${{ env.COA_VERSION }}

    - name: Print version number
      run: npx coa --version

    - name: Run Job
      run: npx coa refresh --config COA_CONFIG
